version: '3.9'

services:
  db_tcc_test:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - ${POSTGRES_PORT_TEST}:5432

  token_cache_tcc_test:
    image: redis
    command: redis-server --requirepass ${REDIS_TOKEN_CACHE_PASSWORD} --user ${REDIS_TOKEN_CACHE_USER} on >${REDIS_TOKEN_CACHE_PASSWORD} ~* allcommands --user default off nopass nocommands
    ports:
      - "${REDIS_TOKEN_CACHE_PORT_TEST}:6379"

  cache_tcc_test:
    image: redis
    command: redis-server --requirepass ${REDIS_CACHE_PASSWORD} --user ${REDIS_CACHE_USER} on >${REDIS_CACHE_PASSWORD} ~* allcommands --user default off nopass nocommands
    ports:
      - "${REDIS_CACHE_PORT_TEST}:6379"
  